language: bash

services:
- docker

env:
  matrix:
  - NEXUS_VERSION=3.27.0 TAGS=0.0.6,latest NEXUS_BUILD=03

script:
- make 

deploy:
  provider: script
  script: bash ${TRAVIS_BUILD_DIR}/release.sh
  on:
    branch: master
