language: bash

services:
- docker

env:
  matrix:
  - NEXUS_VERSION=3.28.1 TAGS=0.0.7,latest NEXUS_BUILD=01

script:
- make 

deploy:
  provider: script
  script: bash ${TRAVIS_BUILD_DIR}/release.sh
  on:
    branch: master
