name: Docker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * 0'
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - bowens/nexus-oss-apk-composer:1.0.0
      - bowens/nexus-oss-apk-composer:latest

  # Run tests for any PRs.
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            bowens/nexus-oss-apk-composer
            ghcr.io/taz77/nexus-oss-apk-composer
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx 1
        uses: docker/setup-buildx-action@v3
      - name: Build and push Latest
        id: docker_build1
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            bowens/nexus-oss-apk-composer:latest
            bowens/nexus-oss-apk-composer:1.0.0
            ghcr.io/taz77/nexus-oss-apk-composer:latest
            ghcr.io/taz77/nexus-oss-apk-composer:1.0.0
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
          fields: repo,commit,message,author # default: repo,commit
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
