name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - 0.0.8
      - latest

  # Run tests for any PRs.
  pull_request:

jobs:
  main:
      env:
        NEXUS_VERSION: latest
        NEXUS_BUILD: 01
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images: name/app # list of Docker images to use as base name for tags
            tag-sha: true # add git short SHA as Docker tag
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DockerUsername }}
            password: ${{ secrets.DockerPassword }}
        -
          name: Set up Docker Buildx 1
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push Latest
          env:
            NEXUS_VERSION: latest
            NEXUS_BUILD: 01
          id: docker_build1
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ steps.docker_meta.outputs.tags }}
