name: Docker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - bowens/nexus-oss-apk-composer:1.0.0
      - bowens/nexus-oss-apk-composer:latest

  # Run tests for any PRs.
  pull_request:

jobs:
  main:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1
          with:
            images: name/app # list of Docker images to use as base name for tags
            tag-sha: true # add git short SHA as Docker tag
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERUSERNAME }}
            password: ${{ secrets.DOCKERPASSWORD }}
        -
          name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        -
          name: Set up Docker Buildx 1
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push Latest
          id: docker_build1
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: |
              bowens/nexus-oss-apk-composer:latest
              bowens/nexus-oss-apk-composer:1.0.0
              ghcr.io/taz77/nexus-oss-apk-composer:latest
              ghcr.io/taz77/nexus-oss-apk-composer:1.0.0
        -
          name: Notify Slack
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            author_name: Integration Test # default: 8398a7@action-slack
            fields: repo,commit,message,author # default: repo,commit
            mention: here
            if_mention: failure,cancelled
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
          if: always() # Pick up events even if the job fails or is canceled.
