name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - 0.0.8
      - latest

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: bowens/nexus-oss-apk-composer
  NEXUS_VERSION: latest
  NEXUS_BUILD: 01
  DOCKER_USERNAME: ${{ secrets.DockerUsername }}
  DOCKER_PASSWORD: ${{ secrets.DockerPassword }}

jobs:
  main:
      runs-on: ubuntu-latest
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DockerUsername }}
            password: ${{ secrets.DockerPassword }}
        -
          name: Set up Docker Buildx 1
          uses: docker/setup-buildx-action@v1
          id: builder1
        -
          name: Build and push Latest
          id: docker_build1
          uses: docker/build-push-action@v2
          with:
            builder: ${{ steps.builder1.outputs.name }}
            push: true
            build-args: |
              NEXUS_VERSION=$NEXUS_VERSION
              NEXUS_BUILD=$NEXUS_BUILD
            tags: ${{ steps.docker_meta.outputs.tags }}
